"use client";

import { useEffect, useState } from "react";
import { Save, ShieldCheck } from "lucide-react";
import { adminFetch } from "@/lib/admin-fetch";

const keys = ["service_fee_percent", "tax_percent", "reservation_minutes", "payment_link_allowlist", "contact_email", "contact_phone"];

export default function SettingsPage() {
  const [settings, setSettings] = useState<Record<string, string>>({});
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { adminFetch<{ settings: Record<string,string> }>("/api/admin/settings").then((data) => setSettings(data.settings)).catch((cause) => setError(cause.message)); }, []);
  async function save() { setError(""); setNotice(""); try { const payload = Object.fromEntries(keys.map((key) => [key, settings[key] || ""])); await adminFetch("/api/admin/settings", { method: "PUT", body: JSON.stringify(payload) }); setNotice("Marketplace settings saved."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Save failed"); } }
  return <div className="max-w-3xl space-y-6"><div><h1 className="font-display text-2xl font-bold">Marketplace settings</h1><p className="mt-1 text-sm text-[#8b9cb8]">Fees, reservation duration, support, and approved payment-link domains.</p></div><div className="rounded-xl border border-[#20352d] bg-[#0f251d] p-5"><div className="grid gap-4 sm:grid-cols-3"><Field label="Service fee (%)"><input className="admin-input" value={settings.service_fee_percent || ""} onChange={(e) => setSettings({ ...settings, service_fee_percent: e.target.value })} /></Field><Field label="Tax (%)"><input className="admin-input" value={settings.tax_percent || ""} onChange={(e) => setSettings({ ...settings, tax_percent: e.target.value })} /></Field><Field label="Reservation minutes"><input className="admin-input" value={settings.reservation_minutes || ""} onChange={(e) => setSettings({ ...settings, reservation_minutes: e.target.value })} /></Field></div><Field label="Approved payment-link domains (comma separated)"><input className="admin-input" value={settings.payment_link_allowlist || ""} onChange={(e) => setSettings({ ...settings, payment_link_allowlist: e.target.value })} /></Field><div className="mt-3 flex items-start gap-2 rounded-lg bg-[#071b13] p-3 text-xs text-[#83978f]"><ShieldCheck className="h-4 w-4 shrink-0 text-[#35e89b]" /> Exact hosts and their subdomains are permitted. HTTPS is always required; credentials should never be included in chat links.</div><div className="grid gap-4 sm:grid-cols-2"><Field label="Support email"><input className="admin-input" value={settings.contact_email || ""} onChange={(e) => setSettings({ ...settings, contact_email: e.target.value })} /></Field><Field label="Support phone"><input className="admin-input" value={settings.contact_phone || ""} onChange={(e) => setSettings({ ...settings, contact_phone: e.target.value })} /></Field></div>{error ? <p className="mt-4 text-sm text-red-300">{error}</p> : null}{notice ? <p className="mt-4 text-sm text-emerald-300">{notice}</p> : null}<button onClick={save} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#35e89b] px-5 py-2.5 text-sm font-bold text-[#062017]"><Save className="h-4 w-4" /> Save settings</button></div><style jsx>{`.admin-input{width:100%;border:1px solid #294139;background:#071b13;border-radius:8px;padding:.65rem .75rem;color:white;font-size:.875rem}`}</style></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="mt-4 block"><span className="mb-1.5 block text-xs text-[#82978f]">{label}</span>{children}</label>; }
